export { colorPaletteDemo } from "./color-palette-demo"
export { ColorPalette } from "./ColorPalette"
export { colorPaletteToSVG } from "./colorPaletteToSVG"
export { getColorPalette } from "./getColorPalette"
export { getRainbowPalette } from "./getRainbowPalette"
export { rainbowPaletteDemo } from "./rainbow-palette-demo"
